### ISSUE TITLE
Configure GitHub Workflow to run coverage validation

### ISSUE THREAD

**Issue by DanielBrito** [DanielBrito/creditas-challenge-suitable-loans#13]
The pipeline flow should fail when code coverage does not meet expectations.

```yaml
# sonar.yaml in .github/workflows

name: Quality Assurance

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run coverage report
        working-directory: loan 
        run: ./gradlew test jacocoReport -i
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: build/reports/jacoco

  sonarqube:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Download Test Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: report
          path: build/reports/jacoco
        working-directory: loan
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add to project

```
